### ISSUE TITLE
c++写入数据到分布式表示例无法运行

### ISSUE THREAD

**Issue by delusionpig** [dolphindb/api-cplusplus#10]
![image](https://user-images.githubusercontent.com/91172056/163924868-19050518-ef20-46ea-986b-2915c83f19d4.png)
代码复制后直接执行：
显示dolphindb::ConstantSP类型用作表达式非法
![image](https://user-images.githubusercontent.com/91172056/163925014-adec72e7-b640-49f4-9004-21f08bf4a22e.png)
![image](https://user-images.githubusercontent.com/91172056/163925051-6f29bfcb-1387-472d-bf42-8b0369873680.png)

**Comment by peeyee** [comment]
完整的程序发看看，看着应该是没引入ConstantSP对应的头文件
