### ISSUE TITLE
C++ api error when compling with Win10

### ISSUE THREAD

**Issue by dbsxdbsx** [dolphindb/api-cplusplus#2]
I am using vs2019,  when compliing，  it is said that some file canot be found, but it seems that it is not used with Visual Studio. 

Then I comment it. it still get errored with:
```
DBConnection conn;
bool ret = conn.connect("localhost", 8848);// raising exception
```
[error picture](https://share.weiyun.com/5QSKMCZ)

**Comment by xiaodanzhang** [comment]
This has been fixed. please try again.
