### ISSUE TITLE
Feature: 建议文档中完善读性能提示

### ISSUE THREAD

**Issue by vrqq** [dolphindb/api-cplusplus#5]
加载table过后，批量按column装入数组，比```getRow()->getMember()->getString()```快很多，建议完善文档。

**Comment by xiaodanzhang** [comment]
谢谢您的建议。我们尽快完善。

**Comment by dzhou284** [comment]
请问一下，你使用getRow()->getMember()->getString()这种方式读取数据，是不是因为受我们Readme中的某个例子误导？如果有，告诉我们一下，我们改过来。如果没有，我们给出一些通用的提高读性能的提示。
